Sprint 4
kvitkina/middle.messenger.praktikum.yandex pull request #5
Opened 2022-11-09 14:45 UTC by kvitkina

2022-11-10 07:40 UTC, maks88sgt requested changes
Привет! Ты хорошо потрудилась, но пока не могу принять работу. Основные замечания:
1. Уязвимости в зависимостях;
2. Проблемы с запуском тестов и слабое покрытие.
Чтобы идти дальше нужно как минимум разобраться с этим, но у меня есть еще несколько пожеланий по проекту:
1. Ты довольно много где отключаешь TS и используешь any. Это не лучшая практика, потому что таким образом мы не получаем никаких бенефитов от использования TS а только лишнюю писанину. Возможно тебе тяжело использовать все возможности языка, но это будет очень полезно в будущем. Пробуй пользоваться приведением типов, созданием своих объявлений, дженериками и не заметишь как полюбишь TS и его abirb/
2. Есть проблемы с функционалом проекта:
-  неправильная работа в Heroku - приложение падает при переходе в профиль
- при перерендарах чатов в списке, чаты заменяются один на другой. Записал видео:
https://user-images.githubusercontent.com/49103217/201027918-9b76e763-6429-49f9-8ddf-92afbb41243b.mp4
3. При создании модалок они перерисовываются по нескольку раз. Видео
https://user-images.githubusercontent.com/49103217/201028334-0cf3f63e-a979-4a84-a7d0-6245e0826585.mp4
4. При смене аватара новая картинка не отображается после загрузки.

2022-11-10 07:40 UTC, maks88sgt commented on .eslintrc.json
> +        "@typescript-eslint/ban-ts-comment": "off"
Глобальное отключение ESLint правил считается не очень хорошей практикой, лучше делать это в каждом конкретном случае если это необходимо, но в целом лучше постараться сделать так, чтобы не пришлось делать этого, ведь эти правила придуманы не просто так и действительно помогают избежать ошибок и сделать код лучше.

2022-11-10 07:40 UTC, maks88sgt commented on package.json
> +        "@types/chai": "^4.3.3",
Хорошей практикой считается использовать фиксированные версии зависимостей (и это было одним из требований в спринте 2). Давай поправим это

2022-11-10 07:40 UTC, maks88sgt commented on package.json
> +        "webpack-dev-server": "^4.11.1"
Отчет по уязвимостям зависимостей выдает пару ошибок. Нужно исправить это (один из основных критериев спринта)
<img width="509" alt="image" src="https://user-images.githubusercontent.com/49103217/201014396-bdcdfe44-0f7f-4e90-9068-bf5b510c2747.png">

2022-11-10 07:40 UTC, maks88sgt commented on src/utils/HTTPTransport.test.ts
> +        instance.get('/signin');
Похоже что неправильно выбран метод для эндпоинта, должен отправляться post запрос

2022-11-10 07:40 UTC, maks88sgt commented on src/utils/HTTPTransport.test.ts
> +        expect(request.method).to.eq('Get');
Здесь будет падать ошибка, т.к. вернется "GET"

2022-11-10 07:40 UTC, maks88sgt commented on package.json
> +            "pre-commit": "npm run lint:fix"
Сюда было бы неплохо добавить прогон тестов, это считается хорошей практикой.

2022-11-10 07:40 UTC, maks88sgt commented on src/utils/HTTPTransport.test.ts
> +describe('HTTPTransport', () => {
Этот набор тестов не работает, т.к. в тестовом окружении нет класса FormData который используется внутри HTTPTransport. Нужно добавить его в начальных установках mocha

2022-11-10 07:40 UTC, maks88sgt commented on src/utils/HTTPTransport.test.ts
> +        // @ts-ignore
В последних версиях TS для таких случаев появилась возможность использовать // @ts-expect-error, который подходит как раз для тестов. 
Можно почитать в чем разница https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html

2022-11-10 07:40 UTC, maks88sgt commented on src/utils/Block.test.ts
> +    it.only('setProps() should update properties', () => {
it.only приведет к тому, что скриптом из package.json будет запускаться только этот тест

2022-11-10 07:40 UTC, maks88sgt commented on src/utils/HTTPTransport.ts
> +                // @ts-ignore
Попробуй вместо ts-ignore пользоваться инструментами TS, например приведение типов 
```suggestion
               resolve(xhr as Response);
```

2022-11-10 07:40 UTC, maks88sgt commented on src/components/Link/index.test.ts
> +describe('Link', () => {
Этот тест приводит к ошибке компиляции TS. Выглядит так, что в настройках mocha неправильно сделано подключение шаблонизатора.

2022-11-13 21:53 UTC, kvitkina commented on package.json
> +        "webpack-dev-server": "^4.11.1"
у handlebars-loader открыт pull request для обновления loader-utils https://github.com/pcardune/handlebars-loader/pull/211

2022-11-14 06:30 UTC, maks88sgt commented
Привет. Спасибо за исправления, но все еще есть проблемы с функционалом чата,, связанные с двойным рендером модалок и неправильным рендером чатов в списке. Давай поправим это, чтобы считать проект завершенным

2022-11-15 10:08 UTC, maks88sgt approved these changes
Теперь все отлично! Удачи на курсе!

2022-11-15 11:58 UTC, merged